<a href="https://colab.research.google.com/github/Shkum/IT_STEP/blob/ML/module2/%D0%94%D0%97_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [1]:
import numpy as np

#Завдання 1

Створіть масив з парними числами між 30 і 70

In [2]:
a = np.array(np.arange(30, 71, 2))
a

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

#Завдання 2
Створіть масив з 10 числами між 0(включно) та 1(не включно) див документацію

In [3]:
a = np.linspace(0,1, 10, endpoint=False)
a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#Завдання 4
Напишіть функцію яка приймає матрицю розміру nxn та повертає матрицю розміру (n+2) x (n+2), на краях якої розміщенні 0.

In [4]:
import numpy as np


def fill_zeros(matrix: np.ndarray):
    n, m = matrix.shape
    result = np.zeros([n + 2, m + 2])
    result[1:-1, 1:-1] = matrix
    return result


a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]).reshape(-1, 3)

print(fill_zeros(a))

[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  0.]
 [ 0.  4.  5.  6.  0.]
 [ 0.  7.  8.  9.  0.]
 [ 0. 10. 11. 12.  0.]
 [ 0.  0.  0.  0.  0.]]


#Завдання 5
У попередьньому масиві змініть тип даних. Виведіть тип даних до та після зміни

In [5]:
print(a.dtype)
# a = a.astype(np.dtypes.Float16DType)  # для чего нужен такой вид записи?
a = a.astype(np.float16)
print(a.dtype)

int64
float16


#Завдання 6
У даному масиві замініть елементи, які дорівнюють\більші\менші за var на -1

In [11]:
x = np.array([1, 5, 3, 8, 6, 5, 7, 4])
var = 5

a = x.copy()
mask = a == var
print(mask)
a[mask] = -1
print(a)

print()

a = x.copy()
mask = a > var
print(mask)
a[mask] = -1
print(a)

print()

a = x.copy()
mask = a < var
print(mask)
a[mask] = -1
print(a)


[False  True False False False  True False False]
[ 1 -1  3  8  6 -1  7  4]

[False False False  True  True False  True False]
[ 1  5  3 -1 -1  5 -1  4]

[ True False  True False False False False  True]
[-1  5 -1  8  6  5  7 -1]


#Завдання 7
Замініть пропущені значення матриці(np.nan) на -1

Дивись np.isnan

In [20]:
X = np.array([[1, 2, np.nan, 4],
              [5, np.nan, np.nan, 4],
              [np.nan, 10, 11, np.nan]])

mask = np.isnan(X)
X[mask] = -1
X

array([[ 1.,  2., -1.,  4.],
       [ 5., -1., -1.,  4.],
       [-1., 10., 11., -1.]])

#Завдання 8
Створіть матрицю розміру 4х6 з випадковими числами. Змініть її розмір на 3х8

In [24]:
a = np.random.random([4,6])
print(a)
print()
a = a.reshape(3, 8)
a

[[6.12949276e-01 7.42583990e-01 1.39190616e-01 2.46454938e-01
  4.11206585e-01 8.88853000e-01]
 [3.51581175e-02 5.82933800e-01 4.56096098e-01 3.98941886e-04
  2.68677861e-01 3.94962248e-01]
 [8.91183325e-01 2.15922292e-01 4.74163362e-01 6.62171808e-01
  9.80149225e-01 8.78303795e-01]
 [4.82561425e-02 6.14135868e-01 4.38426601e-01 3.40328359e-01
  2.84344915e-01 1.92894754e-01]]



array([[6.12949276e-01, 7.42583990e-01, 1.39190616e-01, 2.46454938e-01,
        4.11206585e-01, 8.88853000e-01, 3.51581175e-02, 5.82933800e-01],
       [4.56096098e-01, 3.98941886e-04, 2.68677861e-01, 3.94962248e-01,
        8.91183325e-01, 2.15922292e-01, 4.74163362e-01, 6.62171808e-01],
       [9.80149225e-01, 8.78303795e-01, 4.82561425e-02, 6.14135868e-01,
        4.38426601e-01, 3.40328359e-01, 2.84344915e-01, 1.92894754e-01]])

#Завдання 9
Створіть матрицю з одиниць розміром 3х4. Знайдіть середнє арифметичне(mean) кожного стовпчика

In [33]:
a = np.ones([3, 4])
print(a, '\n')
b = np.mean(a, axis=0)
b

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 



array([1., 1., 1., 1.])

#Завдання 10
Створіть випадкову матрицю розміром 5х6. Округліть значення до одного знаку після коми(np.round). Розмістіть стовпчики так, щоб значення в першому рядку були відсортовані за зростанням

In [72]:
a = np.random.random((5, 6))

print(a)

print()

a = np.round(a, 1)

print(a)

print()

a = a[:, np.argsort(a[0])]

print(a)

print()

a

# как это работает разобрался, но без подсказки gpt не уверен что догадался бы как отсортировать матрицу по первой строке

# тут везде переменаня a является масивом numpy, почему последний вывод отличается? получается это не обычный print()?

[[0.53837648 0.02534403 0.49198635 0.61235747 0.73543264 0.78421825]
 [0.29715472 0.31525271 0.46940313 0.03927313 0.69264587 0.92962322]
 [0.83442164 0.33833658 0.52624591 0.34103467 0.62092823 0.21392767]
 [0.89928347 0.33086181 0.20654648 0.9605892  0.55993202 0.76481858]
 [0.03515046 0.58842687 0.12143408 0.05221079 0.90547716 0.89636275]]

[[0.5 0.  0.5 0.6 0.7 0.8]
 [0.3 0.3 0.5 0.  0.7 0.9]
 [0.8 0.3 0.5 0.3 0.6 0.2]
 [0.9 0.3 0.2 1.  0.6 0.8]
 [0.  0.6 0.1 0.1 0.9 0.9]]

[[0.  0.5 0.5 0.6 0.7 0.8]
 [0.3 0.3 0.5 0.  0.7 0.9]
 [0.3 0.8 0.5 0.3 0.6 0.2]
 [0.3 0.9 0.2 1.  0.6 0.8]
 [0.6 0.  0.1 0.1 0.9 0.9]]



array([[0. , 0.5, 0.5, 0.6, 0.7, 0.8],
       [0.3, 0.3, 0.5, 0. , 0.7, 0.9],
       [0.3, 0.8, 0.5, 0.3, 0.6, 0.2],
       [0.3, 0.9, 0.2, 1. , 0.6, 0.8],
       [0.6, 0. , 0.1, 0.1, 0.9, 0.9]])

#Завдання 11
В даній матриці знайдіть всі елементи зі значенням між 3 і 6

Дивись документацію np.logical_and

In [89]:
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [9, 8, 7, 6, 5],
              [4, 3, 2, 1, 0]])

a = np.logical_and(X > 3, X < 6)
print(a, '\n')
print(X[a])

# вроде работает, надеюсь правильно. Не понятно почему у матриц Х и а одна размерность, а на выходе получается вектор

[[False False False  True  True]
 [False False False False False]
 [False False False False  True]
 [ True False False False False]] 

[4 5 5 4]


#Завдання 12
Створіть випадкову матрицю розміру 5х6. Нормалізуйте стовпчики: від кожного елемента ставпчика відніміть мінімальне значення та поділіть результат на різницю між максимальним та мінімальним елементом.

Після цього всі значення мають бути в межах [0, 1]

In [87]:
a = np.random.random((5, 6))
print(a, '\n')
a = a * 100
a = np.round(a, 0)
print(a, '\n')
max_val = np.max(a, axis=0)
min_val = np.min(a, axis=0)
print(max_val, '\n')
print(min_val, '\n')
a = (a - min_val) / (max_val - min_val)
a = np.round(a, 3)
print(a)

# вроде работает но не уверен что правильно :), а как проверить не знаю

[[0.70250956 0.70804503 0.73840817 0.52181319 0.32327281 0.53301559]
 [0.60360306 0.76540204 0.42479051 0.95720584 0.17648133 0.85141768]
 [0.0119621  0.99889535 0.56048324 0.55340119 0.09658731 0.35983404]
 [0.47292056 0.40746343 0.56729917 0.40025302 0.99435292 0.13782111]
 [0.15488894 0.56972092 0.03516013 0.4975564  0.03507403 0.75404555]] 

[[ 70.  71.  74.  52.  32.  53.]
 [ 60.  77.  42.  96.  18.  85.]
 [  1. 100.  56.  55.  10.  36.]
 [ 47.  41.  57.  40.  99.  14.]
 [ 15.  57.   4.  50.   4.  75.]] 

[ 70. 100.  74.  96.  99.  85.] 

[ 1. 41.  4. 40.  4. 14.] 

[[1.    0.508 1.    0.214 0.295 0.549]
 [0.855 0.61  0.543 1.    0.147 1.   ]
 [0.    1.    0.743 0.268 0.063 0.31 ]
 [0.667 0.    0.757 0.    1.    0.   ]
 [0.203 0.271 0.    0.179 0.    0.859]]
